[package]
name = "todo-list-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
gtk = { version = "0.9.6", package = "gtk4", features = ["v4_18"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"

[build-dependencies]
glib-build-tools = "0.20.0"
